version: '2'
services:
  utils-app:
    image: utils
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_MONGODB_URI=mongodb://utils-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=utils
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  utils-mongodb:
    extends:
      file: mongodb.yml
      service: utils-mongodb
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
